use local Overpass server
git-svn-id: https://openseamap.svn.sourceforge.net/svnroot/openseamap/renderer@855 043453e6-25df-4c13-81b0-d6a77d00cc6f

diff --git a/sport_work/render b/sport_work/render
--- a/sport_work/render
+++ b/sport_work/render
@@ -7,20 +7,21 @@ download () {
 		cat types.txt | while read type; do
 			touch sort.osm
 			while [ -e sort.osm ]; do
-				if [ "$type" = "sport=swimming" ]; then
+#				if [ "$type" = "sport=swimming" ]; then
 #					while ! wget -q -T 1800 -O xapi.osm --limit-rate=500k --post-file=swimming.osm3s http://www.overpass-api.de/api/interpreter; do
-					while ! wget -q -T 1800 -O xapi.osm --limit-rate=500k --post-file=swimming.osm3s http://overpass.osm.rambler.ru/cgi/interpreter; do
-						echo "$(date) wget error - retrying JXAPI" >> log.txt
-						sleep 60
-					done
-				else
+#					while ! wget -q -T 1800 -O xapi.osm --limit-rate=500k --post-file=swimming.osm3s http://overpass.osm.rambler.ru/cgi/interpreter; do
+#						echo "$(date) wget error - retrying JXAPI" >> log.txt
+#						sleep 60
+#					done
+#				else
 #					while ! wget -q -T 1800 --limit-rate=500k -O xapi.osm http://jxapi.openstreetmap.org/xapi/api/0.6/*[$type]; do
 #					while ! wget -q -T 1800 --limit-rate=500k -O xapi.osm http://overpass-api.de/api/xapi?*[$type][@meta]; do
-					while ! wget -q -T 1800 --limit-rate=500k -O xapi.osm http://overpass.osm.rambler.ru/cgi/xapi?*[$type][@meta]; do
-						echo "$(date) wget error - retrying JXAPI" >> log.txt
-						sleep 60
-					done
-				fi
+#					while ! wget -q -T 1800 --limit-rate=500k -O xapi.osm http://overpass.osm.rambler.ru/cgi/xapi?*[$type][@meta]; do
+#						echo "$(date) wget error - retrying JXAPI" >> log.txt
+#						sleep 60
+#					done
+#				fi
+        ./Overpass/translate_xapi "*[$type][@meta]" | ./Overpass/osm3s_query > xapi.osm
 				if osmosis -q --rx file=xapi.osm --s --wx file=sort.osm 2> /dev/null; then
 					rm xapi.osm
 					if [ -e merge.osm ]; then
