revert
git-svn-id: https://openseamap.svn.sourceforge.net/svnroot/openseamap/renderer@909 043453e6-25df-4c13-81b0-d6a77d00cc6f

diff --git a/sports/render b/sports/render
--- a/sports/render
+++ b/sports/render
@@ -7,7 +7,17 @@ download () {
 		cat types.txt | while read type; do
 			touch sort.osm
 			while [ -e sort.osm ]; do
-        ./Overpass/translate_xapi "*[$type][@meta]" | ./Overpass/osm3s_query > xapi.osm 2> /dev/null
+				if [ "$type" = "sport=swimming" ]; then
+					while ! wget -q -T 1800 -O xapi.osm --limit-rate=500k --post-file=swimming.osm3s http://overpass.osm.rambler.ru/cgi/interpreter; do
+						echo "$(date) wget error - retrying JXAPI" >> log.txt
+						sleep 60
+					done
+				else
+					while ! wget -q -T 1800 --limit-rate=500k -O xapi.osm http://overpass.osm.rambler.ru/cgi/xapi?*[$type][@meta]; do
+						echo "$(date) wget error - retrying JXAPI" >> log.txt
+						sleep 60
+					done
+				fi
 				if osmosis -q --rx file=xapi.osm --s --wx file=sort.osm 2> /dev/null; then
 					rm xapi.osm
 					if [ -e merge.osm ]; then
@@ -73,21 +83,18 @@ search () {
           inkscape tmp/panel.svg -e tmp/panel.png -d 90 -a 256:256:512:512 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
           if [ -e tmp/panel.png ]; then
             if [ $(stat tmp/panel.png | cut -f 8 -d' ') -ge 410 ]; then
-              perl ./orp/orp.pl -r ./styles/osm-seamark-sport-z9.xml -b $bb9 -o tmp/panel.svg tmp/panel-z9.osm 2>/dev/null
-              inkscape tmp/panel.svg -e tmp/91011.png -d 11.25 -a 256:256:2304:2304 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
-              if [ $(stat tmp/91011.png | cut -f 8 -d' ') -ge 410 ]; then
-                mv tmp/91011.png sport_tiles/9/$tx9/$ty9.png
+              if [ ! -e tmp/sport_tiles-9-$tx9-$ty9.png ]; then
+                perl ./orp/orp.pl -r ./styles/osm-seamark-sport-z9.xml -b $bb9 -o tmp/panel.svg tmp/panel-z9.osm 2>/dev/null
+                inkscape tmp/panel.svg -e tmp/sport_tiles-9-$tx9-$ty9.png -d 11.25 -a 256:256:2304:2304 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
               fi
-              perl ./orp/orp.pl -r ./styles/osm-seamark-sport-z10.xml -b $bb10 -o tmp/panel.svg tmp/panel-z10.osm 2>/dev/null
-              inkscape tmp/panel.svg -e tmp/91011.png -d 22.5 -a 256:256:1280:1280 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
-              if [ $(stat tmp/91011.png | cut -f 8 -d' ') -ge 410 ]; then
-                mv tmp/91011.png sport_tiles/10/$tx10/$ty10.png
+              if [ ! -e tmp/sport_tiles-10-$tx10-$ty10.png ]; then
+                perl ./orp/orp.pl -r ./styles/osm-seamark-sport-z10.xml -b $bb10 -o tmp/panel.svg tmp/panel-z10.osm 2>/dev/null
+                inkscape tmp/panel.svg -e tmp/sport_tiles-10-$tx10-$ty10.png -d 22.5 -a 256:256:1280:1280 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
               fi
-              perl ./orp/orp.pl -r ./styles/osm-seamark-sport-z11.xml -b $bb11 -o tmp/panel.svg tmp/panel-z11.osm 2>/dev/null
-              inkscape tmp/panel.svg -e tmp/91011.png -d 45 -a 256:256:768:768 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
-              if [ $(stat tmp/91011.png | cut -f 8 -d' ') -ge 410 ]; then
-                mv tmp/91011.png sport_tiles/11/$tx11/$ty11.png
-              fi
+              if [ ! -e tmp/sport_tiles-11-$tx11-$ty11.png ]; then
+                perl ./orp/orp.pl -r ./styles/osm-seamark-sport-z11.xml -b $bb11 -o tmp/panel.svg tmp/panel-z11.osm 2>/dev/null
+                inkscape tmp/panel.svg -e tmp/sport_tiles-11-$tx11-$ty11.png -d 45 -a 256:256:768:768 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
+              fi                                                                                                          
               cp tmp/panel-z12.osm tmp/$tx\_$ty\_$bb\_12.osm
             fi
           fi
@@ -141,7 +148,9 @@ while true; do
 		done
 		echo "$(date) Resumed" >> log.txt
 	fi
-	latest=$(cat datestamp)
-	sleep 14400
+		latest=$(cat datestamp)
+	if [ $previous == $latest ]; then
+		sleep 14400
+	fi
 	previous=$latest
 done
