jxapi download improvement
git-svn-id: https://openseamap.svn.sourceforge.net/svnroot/openseamap/renderer@385 043453e6-25df-4c13-81b0-d6a77d00cc6f

diff --git a/work/render b/work/render
--- a/work/render
+++ b/work/render
@@ -3,27 +3,31 @@
 download () {
 	echo "$(date) fetching next db file" >> log.txt
 	if [ -e merge.osm ]; then rm merge.osm; fi
-	cat types.txt | while read type; do
-		while ! wget -q -T 1800 -O xapi.osm http://jxapi.openstreetmap.org/xapi/api/0.6/*[seamark:type=$type]; do
-			echo "$(date) wget error - retrying JXAPI" >> log.txt
-			sleep 60
+	while [ ! -e merge.osm ]; do
+		cat types.txt | while read type; do
+			touch sort.osm
+			while [ -e sort.osm ]; do
+				while ! wget -q -T 300 -O xapi.osm http://jxapi.openstreetmap.org/xapi/api/0.6/*[seamark:type=$type]; do
+					echo "$(date) wget error - retrying JXAPI" >> log.txt
+					sleep 60
+				done
+				if osmosis -q --rx file=xapi.osm --s --wx file=sort.osm 2> /dev/null; then
+					rm xapi.osm
+					if [ -e merge.osm ]; then
+						osmosis -q --rx file=merge.osm --rx file=sort.osm --m --wx file=tmp.osm 2> /dev/null
+						mv tmp.osm merge.osm
+						rm sort.osm
+					else
+						mv sort.osm merge.osm
+					fi
+				else
+					echo "$(date) bad data" >> log.txt
+					touch sort.osm
+				fi
+			done
 		done
-		if osmosis -q --rx file=xapi.osm --s --wx file=sort.osm 2> /dev/null; then
-			rm xapi.osm
-			if [ -e merge.osm ]; then
-				osmosis -q --rx file=merge.osm --rx file=sort.osm --m --wx file=tmp.osm 2> /dev/null
-				mv tmp.osm merge.osm
-				rm sort.osm
-			else
-				mv sort.osm merge.osm
-			fi
-		else
-			echo "$(date) bad data" >> log.txt
-			if [ -e merge.osm ]; then rm merge.osm; fi
-			break
-		fi
 	done
-	if [ -e merge.osm ]; then mv merge.osm next.osm; fi
+	mv merge.osm next.osm
 	echo "$(date) successful download" >> log.txt
 }
 
@@ -89,7 +93,7 @@ tile () {
 	inkscape panel.svg -e panel.png -d 90 -a 256:256:512:512 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
 	if [ $(stat panel.png | cut -f 8 -d' ') -ge 410 ]; then
 		for ((k=12; k<=18; k=k+1)); do
-			perl ../olaf/orp.pl -r ../SeaMapStyles/osm-seamark-z$k.xml -b $3 -o panel_$k.svg panel.osm 2>/dev/null
+			perl ../orp/orp.pl -r ../SeaMapStyles/osm-seamark-z$k.xml -b $3 -o panel_$k.svg panel.osm 2>/dev/null
 		done;
 		mkdir -p tiles/12/$1
 		filename="tiles/12/$1/$2.png"
@@ -147,13 +151,15 @@ if [ $# -eq 0 ]; then
 	else
 		previous=0
 	fi
-else
+elif [ $# -eq 1 ]; then
 	previous=$1
+else
+	previous=0
 fi
 
-if [ $# -eq 1 ]; then
-	search 0 0 0
-	echo "$(date) Rendering complete" >> log.txt
+if [ $# -eq 3 ]; then
+	search $1 $2 $3
+	echo "$(date) Rendering of $1 $2 $3 complete" >> log.txt
 	exit
 fi
 
@@ -171,6 +177,10 @@ while true; do
 	done
 	echo "$latest" > datestamp
 	echo "$(date) Rendered to latest timestamp: $latest" >> log.txt
+	if [ -e stop ]; then
+		echo "$(date) Stopped" >> log.txt
+		exit
+	fi
 	if [ $previous == $latest ]; then
 		sleep 3600
 	fi
