wild-card seamark download
git-svn-id: https://openseamap.svn.sourceforge.net/svnroot/openseamap/renderer@721 043453e6-25df-4c13-81b0-d6a77d00cc6f

diff --git a/work/render b/work/render
--- a/work/render
+++ b/work/render
@@ -2,37 +2,42 @@
 
 download () {
 	echo "$(date) fetching next db file" >> log.txt
-	if [ -e merge.osm ]; then rm merge.osm; fi
-	while [ ! -e merge.osm ]; do
-		cat types.txt | while read type; do
-			touch sort.osm
-			while [ -e sort.osm ]; do
-#				while ! wget -q -T 1800 --limit-rate=500k -O xapi.osm http://jxapi.openstreetmap.org/xapi/api/0.6/*[seamark:type=$type]; do
-#				while ! wget -q -T 1800 --limit-rate=500k -O xapi.osm http://overpass-api.de/api/xapi?*[seamark:type=$type][@meta]; do
-				sed s/*/$type/ types.osm3s > get.osm3s
-#				while !	wget -q -T 1800 -O xapi.osm --limit-rate=500k --post-file=get.osm3s http://www.overpass-api.de/api/interpreter; do
-				while !	wget -q -T 1800 -O xapi.osm --limit-rate=500k --post-file=get.osm3s http://overpass.osm.rambler.ru/cgi/interpreter; do
+#	if [ -e merge.osm ]; then rm merge.osm; fi
+#	while [ ! -e merge.osm ]; do
+#		cat types.txt | while read type; do
+#			touch sort.osm
+#			while [ -e sort.osm ]; do
+##				while ! wget -q -T 1800 --limit-rate=500k -O xapi.osm http://jxapi.openstreetmap.org/xapi/api/0.6/*[seamark:type=$type]; do
+##				while ! wget -q -T 1800 --limit-rate=500k -O xapi.osm http://overpass-api.de/api/xapi?*[seamark:type=$type][@meta]; do
+#				sed s/*/$type/ types.osm3s > get.osm3s
+##				while !	wget -q -T 1800 -O xapi.osm --limit-rate=500k --post-file=get.osm3s http://www.overpass-api.de/api/interpreter; do
+#				while !	wget -q -T 1800 -O xapi.osm --limit-rate=500k --post-file=get.osm3s http://overpass.osm.rambler.ru/cgi/interpreter; do
+#					echo "$(date) wget error - retrying JXAPI" >> log.txt
+#					sleep 60
+#				done
+#				if osmosis -q --rx file=xapi.osm --s --wx file=sort.osm 2> /dev/null; then
+#					rm xapi.osm
+#					if [ -e merge.osm ]; then
+#						osmosis -q --rx file=merge.osm --rx file=sort.osm --m --wx file=tmp.osm 2> /dev/null
+#						mv tmp.osm merge.osm
+#						rm sort.osm
+#					else
+#						mv sort.osm merge.osm
+#					fi
+#				else
+#					echo "$(date) bad data" >> log.txt
+#					touch sort.osm
+#				fi
+#			done
+#		done
+#	done
+				while ! wget -q -T 1800 --limit-rate=500k -O world.osm http://overpass.osm.rambler.ru/cgi/xapi?*[seamark:type=$type][@meta]; do
 					echo "$(date) wget error - retrying JXAPI" >> log.txt
 					sleep 60
 				done
-				if osmosis -q --rx file=xapi.osm --s --wx file=sort.osm 2> /dev/null; then
-					rm xapi.osm
-					if [ -e merge.osm ]; then
-						osmosis -q --rx file=merge.osm --rx file=sort.osm --m --wx file=tmp.osm 2> /dev/null
-						mv tmp.osm merge.osm
-						rm sort.osm
-					else
-						mv sort.osm merge.osm
-					fi
-				else
-					echo "$(date) bad data" >> log.txt
-					touch sort.osm
-				fi
-			done
-		done
-	done
-	../smfilter/smfilter -a 0.01 < merge.osm > next.osm
-	mv merge.osm world.osm
+	../smfilter/smfilter -a 0.01 < world.osm > next.osm
+#	../smfilter/smfilter -a 0.01 < merge.osm > next.osm
+#	mv merge.osm world.osm
 	echo "$(date) successful download" >> log.txt
 }
 
